// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"itamconnect/ent/internal"
	"itamconnect/ent/mentor"
	"itamconnect/ent/predicate"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// MentorDelete is the builder for deleting a Mentor entity.
type MentorDelete struct {
	config
	hooks    []Hook
	mutation *MentorMutation
}

// Where appends a list predicates to the MentorDelete builder.
func (md *MentorDelete) Where(ps ...predicate.Mentor) *MentorDelete {
	md.mutation.Where(ps...)
	return md
}

// Exec executes the deletion query and returns how many vertices were deleted.
func (md *MentorDelete) Exec(ctx context.Context) (int, error) {
	return withHooks(ctx, md.sqlExec, md.mutation, md.hooks)
}

// ExecX is like Exec, but panics if an error occurs.
func (md *MentorDelete) ExecX(ctx context.Context) int {
	n, err := md.Exec(ctx)
	if err != nil {
		panic(err)
	}
	return n
}

func (md *MentorDelete) sqlExec(ctx context.Context) (int, error) {
	_spec := sqlgraph.NewDeleteSpec(mentor.Table, sqlgraph.NewFieldSpec(mentor.FieldID, field.TypeInt))
	_spec.Node.Schema = md.schemaConfig.Mentor
	ctx = internal.NewSchemaConfigContext(ctx, md.schemaConfig)
	if ps := md.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	affected, err := sqlgraph.DeleteNodes(ctx, md.driver, _spec)
	if err != nil && sqlgraph.IsConstraintError(err) {
		err = &ConstraintError{msg: err.Error(), wrap: err}
	}
	md.mutation.done = true
	return affected, err
}

// MentorDeleteOne is the builder for deleting a single Mentor entity.
type MentorDeleteOne struct {
	md *MentorDelete
}

// Where appends a list predicates to the MentorDelete builder.
func (mdo *MentorDeleteOne) Where(ps ...predicate.Mentor) *MentorDeleteOne {
	mdo.md.mutation.Where(ps...)
	return mdo
}

// Exec executes the deletion query.
func (mdo *MentorDeleteOne) Exec(ctx context.Context) error {
	n, err := mdo.md.Exec(ctx)
	switch {
	case err != nil:
		return err
	case n == 0:
		return &NotFoundError{mentor.Label}
	default:
		return nil
	}
}

// ExecX is like Exec, but panics if an error occurs.
func (mdo *MentorDeleteOne) ExecX(ctx context.Context) {
	if err := mdo.Exec(ctx); err != nil {
		panic(err)
	}
}
