// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"database/sql/driver"
	"fmt"
	"itamconnect/ent/internal"
	"itamconnect/ent/match"
	"itamconnect/ent/menti"
	"itamconnect/ent/mentor"
	"itamconnect/ent/predicate"
	"itamconnect/ent/user"
	"math"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// MentiQuery is the builder for querying Menti entities.
type MentiQuery struct {
	config
	ctx         *QueryContext
	order       []menti.OrderOption
	inters      []Interceptor
	predicates  []predicate.Menti
	withUser    *UserQuery
	withMentors *MentorQuery
	withMatches *MatchQuery
	// intermediate query (i.e. traversal path).
	sql  *sql.Selector
	path func(context.Context) (*sql.Selector, error)
}

// Where adds a new predicate for the MentiQuery builder.
func (mq *MentiQuery) Where(ps ...predicate.Menti) *MentiQuery {
	mq.predicates = append(mq.predicates, ps...)
	return mq
}

// Limit the number of records to be returned by this query.
func (mq *MentiQuery) Limit(limit int) *MentiQuery {
	mq.ctx.Limit = &limit
	return mq
}

// Offset to start from.
func (mq *MentiQuery) Offset(offset int) *MentiQuery {
	mq.ctx.Offset = &offset
	return mq
}

// Unique configures the query builder to filter duplicate records on query.
// By default, unique is set to true, and can be disabled using this method.
func (mq *MentiQuery) Unique(unique bool) *MentiQuery {
	mq.ctx.Unique = &unique
	return mq
}

// Order specifies how the records should be ordered.
func (mq *MentiQuery) Order(o ...menti.OrderOption) *MentiQuery {
	mq.order = append(mq.order, o...)
	return mq
}

// QueryUser chains the current query on the "user" edge.
func (mq *MentiQuery) QueryUser() *UserQuery {
	query := (&UserClient{config: mq.config}).Query()
	query.path = func(ctx context.Context) (fromU *sql.Selector, err error) {
		if err := mq.prepareQuery(ctx); err != nil {
			return nil, err
		}
		selector := mq.sqlQuery(ctx)
		if err := selector.Err(); err != nil {
			return nil, err
		}
		step := sqlgraph.NewStep(
			sqlgraph.From(menti.Table, menti.FieldID, selector),
			sqlgraph.To(user.Table, user.FieldID),
			sqlgraph.Edge(sqlgraph.O2M, true, menti.UserTable, menti.UserColumn),
		)
		schemaConfig := mq.schemaConfig
		step.To.Schema = schemaConfig.User
		step.Edge.Schema = schemaConfig.User
		fromU = sqlgraph.SetNeighbors(mq.driver.Dialect(), step)
		return fromU, nil
	}
	return query
}

// QueryMentors chains the current query on the "mentors" edge.
func (mq *MentiQuery) QueryMentors() *MentorQuery {
	query := (&MentorClient{config: mq.config}).Query()
	query.path = func(ctx context.Context) (fromU *sql.Selector, err error) {
		if err := mq.prepareQuery(ctx); err != nil {
			return nil, err
		}
		selector := mq.sqlQuery(ctx)
		if err := selector.Err(); err != nil {
			return nil, err
		}
		step := sqlgraph.NewStep(
			sqlgraph.From(menti.Table, menti.FieldID, selector),
			sqlgraph.To(mentor.Table, mentor.FieldID),
			sqlgraph.Edge(sqlgraph.M2M, true, menti.MentorsTable, menti.MentorsPrimaryKey...),
		)
		schemaConfig := mq.schemaConfig
		step.To.Schema = schemaConfig.Mentor
		step.Edge.Schema = schemaConfig.Match
		fromU = sqlgraph.SetNeighbors(mq.driver.Dialect(), step)
		return fromU, nil
	}
	return query
}

// QueryMatches chains the current query on the "matches" edge.
func (mq *MentiQuery) QueryMatches() *MatchQuery {
	query := (&MatchClient{config: mq.config}).Query()
	query.path = func(ctx context.Context) (fromU *sql.Selector, err error) {
		if err := mq.prepareQuery(ctx); err != nil {
			return nil, err
		}
		selector := mq.sqlQuery(ctx)
		if err := selector.Err(); err != nil {
			return nil, err
		}
		step := sqlgraph.NewStep(
			sqlgraph.From(menti.Table, menti.FieldID, selector),
			sqlgraph.To(match.Table, match.FieldID),
			sqlgraph.Edge(sqlgraph.O2M, true, menti.MatchesTable, menti.MatchesColumn),
		)
		schemaConfig := mq.schemaConfig
		step.To.Schema = schemaConfig.Match
		step.Edge.Schema = schemaConfig.Match
		fromU = sqlgraph.SetNeighbors(mq.driver.Dialect(), step)
		return fromU, nil
	}
	return query
}

// First returns the first Menti entity from the query.
// Returns a *NotFoundError when no Menti was found.
func (mq *MentiQuery) First(ctx context.Context) (*Menti, error) {
	nodes, err := mq.Limit(1).All(setContextOp(ctx, mq.ctx, "First"))
	if err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nil, &NotFoundError{menti.Label}
	}
	return nodes[0], nil
}

// FirstX is like First, but panics if an error occurs.
func (mq *MentiQuery) FirstX(ctx context.Context) *Menti {
	node, err := mq.First(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return node
}

// FirstID returns the first Menti ID from the query.
// Returns a *NotFoundError when no Menti ID was found.
func (mq *MentiQuery) FirstID(ctx context.Context) (id int, err error) {
	var ids []int
	if ids, err = mq.Limit(1).IDs(setContextOp(ctx, mq.ctx, "FirstID")); err != nil {
		return
	}
	if len(ids) == 0 {
		err = &NotFoundError{menti.Label}
		return
	}
	return ids[0], nil
}

// FirstIDX is like FirstID, but panics if an error occurs.
func (mq *MentiQuery) FirstIDX(ctx context.Context) int {
	id, err := mq.FirstID(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return id
}

// Only returns a single Menti entity found by the query, ensuring it only returns one.
// Returns a *NotSingularError when more than one Menti entity is found.
// Returns a *NotFoundError when no Menti entities are found.
func (mq *MentiQuery) Only(ctx context.Context) (*Menti, error) {
	nodes, err := mq.Limit(2).All(setContextOp(ctx, mq.ctx, "Only"))
	if err != nil {
		return nil, err
	}
	switch len(nodes) {
	case 1:
		return nodes[0], nil
	case 0:
		return nil, &NotFoundError{menti.Label}
	default:
		return nil, &NotSingularError{menti.Label}
	}
}

// OnlyX is like Only, but panics if an error occurs.
func (mq *MentiQuery) OnlyX(ctx context.Context) *Menti {
	node, err := mq.Only(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// OnlyID is like Only, but returns the only Menti ID in the query.
// Returns a *NotSingularError when more than one Menti ID is found.
// Returns a *NotFoundError when no entities are found.
func (mq *MentiQuery) OnlyID(ctx context.Context) (id int, err error) {
	var ids []int
	if ids, err = mq.Limit(2).IDs(setContextOp(ctx, mq.ctx, "OnlyID")); err != nil {
		return
	}
	switch len(ids) {
	case 1:
		id = ids[0]
	case 0:
		err = &NotFoundError{menti.Label}
	default:
		err = &NotSingularError{menti.Label}
	}
	return
}

// OnlyIDX is like OnlyID, but panics if an error occurs.
func (mq *MentiQuery) OnlyIDX(ctx context.Context) int {
	id, err := mq.OnlyID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// All executes the query and returns a list of Mentis.
func (mq *MentiQuery) All(ctx context.Context) ([]*Menti, error) {
	ctx = setContextOp(ctx, mq.ctx, "All")
	if err := mq.prepareQuery(ctx); err != nil {
		return nil, err
	}
	qr := querierAll[[]*Menti, *MentiQuery]()
	return withInterceptors[[]*Menti](ctx, mq, qr, mq.inters)
}

// AllX is like All, but panics if an error occurs.
func (mq *MentiQuery) AllX(ctx context.Context) []*Menti {
	nodes, err := mq.All(ctx)
	if err != nil {
		panic(err)
	}
	return nodes
}

// IDs executes the query and returns a list of Menti IDs.
func (mq *MentiQuery) IDs(ctx context.Context) (ids []int, err error) {
	if mq.ctx.Unique == nil && mq.path != nil {
		mq.Unique(true)
	}
	ctx = setContextOp(ctx, mq.ctx, "IDs")
	if err = mq.Select(menti.FieldID).Scan(ctx, &ids); err != nil {
		return nil, err
	}
	return ids, nil
}

// IDsX is like IDs, but panics if an error occurs.
func (mq *MentiQuery) IDsX(ctx context.Context) []int {
	ids, err := mq.IDs(ctx)
	if err != nil {
		panic(err)
	}
	return ids
}

// Count returns the count of the given query.
func (mq *MentiQuery) Count(ctx context.Context) (int, error) {
	ctx = setContextOp(ctx, mq.ctx, "Count")
	if err := mq.prepareQuery(ctx); err != nil {
		return 0, err
	}
	return withInterceptors[int](ctx, mq, querierCount[*MentiQuery](), mq.inters)
}

// CountX is like Count, but panics if an error occurs.
func (mq *MentiQuery) CountX(ctx context.Context) int {
	count, err := mq.Count(ctx)
	if err != nil {
		panic(err)
	}
	return count
}

// Exist returns true if the query has elements in the graph.
func (mq *MentiQuery) Exist(ctx context.Context) (bool, error) {
	ctx = setContextOp(ctx, mq.ctx, "Exist")
	switch _, err := mq.FirstID(ctx); {
	case IsNotFound(err):
		return false, nil
	case err != nil:
		return false, fmt.Errorf("ent: check existence: %w", err)
	default:
		return true, nil
	}
}

// ExistX is like Exist, but panics if an error occurs.
func (mq *MentiQuery) ExistX(ctx context.Context) bool {
	exist, err := mq.Exist(ctx)
	if err != nil {
		panic(err)
	}
	return exist
}

// Clone returns a duplicate of the MentiQuery builder, including all associated steps. It can be
// used to prepare common query builders and use them differently after the clone is made.
func (mq *MentiQuery) Clone() *MentiQuery {
	if mq == nil {
		return nil
	}
	return &MentiQuery{
		config:      mq.config,
		ctx:         mq.ctx.Clone(),
		order:       append([]menti.OrderOption{}, mq.order...),
		inters:      append([]Interceptor{}, mq.inters...),
		predicates:  append([]predicate.Menti{}, mq.predicates...),
		withUser:    mq.withUser.Clone(),
		withMentors: mq.withMentors.Clone(),
		withMatches: mq.withMatches.Clone(),
		// clone intermediate query.
		sql:  mq.sql.Clone(),
		path: mq.path,
	}
}

// WithUser tells the query-builder to eager-load the nodes that are connected to
// the "user" edge. The optional arguments are used to configure the query builder of the edge.
func (mq *MentiQuery) WithUser(opts ...func(*UserQuery)) *MentiQuery {
	query := (&UserClient{config: mq.config}).Query()
	for _, opt := range opts {
		opt(query)
	}
	mq.withUser = query
	return mq
}

// WithMentors tells the query-builder to eager-load the nodes that are connected to
// the "mentors" edge. The optional arguments are used to configure the query builder of the edge.
func (mq *MentiQuery) WithMentors(opts ...func(*MentorQuery)) *MentiQuery {
	query := (&MentorClient{config: mq.config}).Query()
	for _, opt := range opts {
		opt(query)
	}
	mq.withMentors = query
	return mq
}

// WithMatches tells the query-builder to eager-load the nodes that are connected to
// the "matches" edge. The optional arguments are used to configure the query builder of the edge.
func (mq *MentiQuery) WithMatches(opts ...func(*MatchQuery)) *MentiQuery {
	query := (&MatchClient{config: mq.config}).Query()
	for _, opt := range opts {
		opt(query)
	}
	mq.withMatches = query
	return mq
}

// GroupBy is used to group vertices by one or more fields/columns.
// It is often used with aggregate functions, like: count, max, mean, min, sum.
func (mq *MentiQuery) GroupBy(field string, fields ...string) *MentiGroupBy {
	mq.ctx.Fields = append([]string{field}, fields...)
	grbuild := &MentiGroupBy{build: mq}
	grbuild.flds = &mq.ctx.Fields
	grbuild.label = menti.Label
	grbuild.scan = grbuild.Scan
	return grbuild
}

// Select allows the selection one or more fields/columns for the given query,
// instead of selecting all fields in the entity.
func (mq *MentiQuery) Select(fields ...string) *MentiSelect {
	mq.ctx.Fields = append(mq.ctx.Fields, fields...)
	sbuild := &MentiSelect{MentiQuery: mq}
	sbuild.label = menti.Label
	sbuild.flds, sbuild.scan = &mq.ctx.Fields, sbuild.Scan
	return sbuild
}

// Aggregate returns a MentiSelect configured with the given aggregations.
func (mq *MentiQuery) Aggregate(fns ...AggregateFunc) *MentiSelect {
	return mq.Select().Aggregate(fns...)
}

func (mq *MentiQuery) prepareQuery(ctx context.Context) error {
	for _, inter := range mq.inters {
		if inter == nil {
			return fmt.Errorf("ent: uninitialized interceptor (forgotten import ent/runtime?)")
		}
		if trv, ok := inter.(Traverser); ok {
			if err := trv.Traverse(ctx, mq); err != nil {
				return err
			}
		}
	}
	for _, f := range mq.ctx.Fields {
		if !menti.ValidColumn(f) {
			return &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
		}
	}
	if mq.path != nil {
		prev, err := mq.path(ctx)
		if err != nil {
			return err
		}
		mq.sql = prev
	}
	return nil
}

func (mq *MentiQuery) sqlAll(ctx context.Context, hooks ...queryHook) ([]*Menti, error) {
	var (
		nodes       = []*Menti{}
		_spec       = mq.querySpec()
		loadedTypes = [3]bool{
			mq.withUser != nil,
			mq.withMentors != nil,
			mq.withMatches != nil,
		}
	)
	_spec.ScanValues = func(columns []string) ([]any, error) {
		return (*Menti).scanValues(nil, columns)
	}
	_spec.Assign = func(columns []string, values []any) error {
		node := &Menti{config: mq.config}
		nodes = append(nodes, node)
		node.Edges.loadedTypes = loadedTypes
		return node.assignValues(columns, values)
	}
	_spec.Node.Schema = mq.schemaConfig.Menti
	ctx = internal.NewSchemaConfigContext(ctx, mq.schemaConfig)
	for i := range hooks {
		hooks[i](ctx, _spec)
	}
	if err := sqlgraph.QueryNodes(ctx, mq.driver, _spec); err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nodes, nil
	}
	if query := mq.withUser; query != nil {
		if err := mq.loadUser(ctx, query, nodes,
			func(n *Menti) { n.Edges.User = []*User{} },
			func(n *Menti, e *User) { n.Edges.User = append(n.Edges.User, e) }); err != nil {
			return nil, err
		}
	}
	if query := mq.withMentors; query != nil {
		if err := mq.loadMentors(ctx, query, nodes,
			func(n *Menti) { n.Edges.Mentors = []*Mentor{} },
			func(n *Menti, e *Mentor) { n.Edges.Mentors = append(n.Edges.Mentors, e) }); err != nil {
			return nil, err
		}
	}
	if query := mq.withMatches; query != nil {
		if err := mq.loadMatches(ctx, query, nodes,
			func(n *Menti) { n.Edges.Matches = []*Match{} },
			func(n *Menti, e *Match) { n.Edges.Matches = append(n.Edges.Matches, e) }); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

func (mq *MentiQuery) loadUser(ctx context.Context, query *UserQuery, nodes []*Menti, init func(*Menti), assign func(*Menti, *User)) error {
	fks := make([]driver.Value, 0, len(nodes))
	nodeids := make(map[int]*Menti)
	for i := range nodes {
		fks = append(fks, nodes[i].ID)
		nodeids[nodes[i].ID] = nodes[i]
		if init != nil {
			init(nodes[i])
		}
	}
	query.withFKs = true
	query.Where(predicate.User(func(s *sql.Selector) {
		s.Where(sql.InValues(s.C(menti.UserColumn), fks...))
	}))
	neighbors, err := query.All(ctx)
	if err != nil {
		return err
	}
	for _, n := range neighbors {
		fk := n.user_menti
		if fk == nil {
			return fmt.Errorf(`foreign-key "user_menti" is nil for node %v`, n.ID)
		}
		node, ok := nodeids[*fk]
		if !ok {
			return fmt.Errorf(`unexpected referenced foreign-key "user_menti" returned %v for node %v`, *fk, n.ID)
		}
		assign(node, n)
	}
	return nil
}
func (mq *MentiQuery) loadMentors(ctx context.Context, query *MentorQuery, nodes []*Menti, init func(*Menti), assign func(*Menti, *Mentor)) error {
	edgeIDs := make([]driver.Value, len(nodes))
	byID := make(map[int]*Menti)
	nids := make(map[int]map[*Menti]struct{})
	for i, node := range nodes {
		edgeIDs[i] = node.ID
		byID[node.ID] = node
		if init != nil {
			init(node)
		}
	}
	query.Where(func(s *sql.Selector) {
		joinT := sql.Table(menti.MentorsTable)
		joinT.Schema(mq.schemaConfig.Match)
		s.Join(joinT).On(s.C(mentor.FieldID), joinT.C(menti.MentorsPrimaryKey[0]))
		s.Where(sql.InValues(joinT.C(menti.MentorsPrimaryKey[1]), edgeIDs...))
		columns := s.SelectedColumns()
		s.Select(joinT.C(menti.MentorsPrimaryKey[1]))
		s.AppendSelect(columns...)
		s.SetDistinct(false)
	})
	if err := query.prepareQuery(ctx); err != nil {
		return err
	}
	qr := QuerierFunc(func(ctx context.Context, q Query) (Value, error) {
		return query.sqlAll(ctx, func(_ context.Context, spec *sqlgraph.QuerySpec) {
			assign := spec.Assign
			values := spec.ScanValues
			spec.ScanValues = func(columns []string) ([]any, error) {
				values, err := values(columns[1:])
				if err != nil {
					return nil, err
				}
				return append([]any{new(sql.NullInt64)}, values...), nil
			}
			spec.Assign = func(columns []string, values []any) error {
				outValue := int(values[0].(*sql.NullInt64).Int64)
				inValue := int(values[1].(*sql.NullInt64).Int64)
				if nids[inValue] == nil {
					nids[inValue] = map[*Menti]struct{}{byID[outValue]: {}}
					return assign(columns[1:], values[1:])
				}
				nids[inValue][byID[outValue]] = struct{}{}
				return nil
			}
		})
	})
	neighbors, err := withInterceptors[[]*Mentor](ctx, query, qr, query.inters)
	if err != nil {
		return err
	}
	for _, n := range neighbors {
		nodes, ok := nids[n.ID]
		if !ok {
			return fmt.Errorf(`unexpected "mentors" node returned %v`, n.ID)
		}
		for kn := range nodes {
			assign(kn, n)
		}
	}
	return nil
}
func (mq *MentiQuery) loadMatches(ctx context.Context, query *MatchQuery, nodes []*Menti, init func(*Menti), assign func(*Menti, *Match)) error {
	fks := make([]driver.Value, 0, len(nodes))
	nodeids := make(map[int]*Menti)
	for i := range nodes {
		fks = append(fks, nodes[i].ID)
		nodeids[nodes[i].ID] = nodes[i]
		if init != nil {
			init(nodes[i])
		}
	}
	if len(query.ctx.Fields) > 0 {
		query.ctx.AppendFieldOnce(match.FieldMentiID)
	}
	query.Where(predicate.Match(func(s *sql.Selector) {
		s.Where(sql.InValues(s.C(menti.MatchesColumn), fks...))
	}))
	neighbors, err := query.All(ctx)
	if err != nil {
		return err
	}
	for _, n := range neighbors {
		fk := n.MentiID
		node, ok := nodeids[fk]
		if !ok {
			return fmt.Errorf(`unexpected referenced foreign-key "menti_id" returned %v for node %v`, fk, n.ID)
		}
		assign(node, n)
	}
	return nil
}

func (mq *MentiQuery) sqlCount(ctx context.Context) (int, error) {
	_spec := mq.querySpec()
	_spec.Node.Schema = mq.schemaConfig.Menti
	ctx = internal.NewSchemaConfigContext(ctx, mq.schemaConfig)
	_spec.Node.Columns = mq.ctx.Fields
	if len(mq.ctx.Fields) > 0 {
		_spec.Unique = mq.ctx.Unique != nil && *mq.ctx.Unique
	}
	return sqlgraph.CountNodes(ctx, mq.driver, _spec)
}

func (mq *MentiQuery) querySpec() *sqlgraph.QuerySpec {
	_spec := sqlgraph.NewQuerySpec(menti.Table, menti.Columns, sqlgraph.NewFieldSpec(menti.FieldID, field.TypeInt))
	_spec.From = mq.sql
	if unique := mq.ctx.Unique; unique != nil {
		_spec.Unique = *unique
	} else if mq.path != nil {
		_spec.Unique = true
	}
	if fields := mq.ctx.Fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, menti.FieldID)
		for i := range fields {
			if fields[i] != menti.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, fields[i])
			}
		}
	}
	if ps := mq.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if limit := mq.ctx.Limit; limit != nil {
		_spec.Limit = *limit
	}
	if offset := mq.ctx.Offset; offset != nil {
		_spec.Offset = *offset
	}
	if ps := mq.order; len(ps) > 0 {
		_spec.Order = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	return _spec
}

func (mq *MentiQuery) sqlQuery(ctx context.Context) *sql.Selector {
	builder := sql.Dialect(mq.driver.Dialect())
	t1 := builder.Table(menti.Table)
	columns := mq.ctx.Fields
	if len(columns) == 0 {
		columns = menti.Columns
	}
	selector := builder.Select(t1.Columns(columns...)...).From(t1)
	if mq.sql != nil {
		selector = mq.sql
		selector.Select(selector.Columns(columns...)...)
	}
	if mq.ctx.Unique != nil && *mq.ctx.Unique {
		selector.Distinct()
	}
	t1.Schema(mq.schemaConfig.Menti)
	ctx = internal.NewSchemaConfigContext(ctx, mq.schemaConfig)
	selector.WithContext(ctx)
	for _, p := range mq.predicates {
		p(selector)
	}
	for _, p := range mq.order {
		p(selector)
	}
	if offset := mq.ctx.Offset; offset != nil {
		// limit is mandatory for offset clause. We start
		// with default value, and override it below if needed.
		selector.Offset(*offset).Limit(math.MaxInt32)
	}
	if limit := mq.ctx.Limit; limit != nil {
		selector.Limit(*limit)
	}
	return selector
}

// MentiGroupBy is the group-by builder for Menti entities.
type MentiGroupBy struct {
	selector
	build *MentiQuery
}

// Aggregate adds the given aggregation functions to the group-by query.
func (mgb *MentiGroupBy) Aggregate(fns ...AggregateFunc) *MentiGroupBy {
	mgb.fns = append(mgb.fns, fns...)
	return mgb
}

// Scan applies the selector query and scans the result into the given value.
func (mgb *MentiGroupBy) Scan(ctx context.Context, v any) error {
	ctx = setContextOp(ctx, mgb.build.ctx, "GroupBy")
	if err := mgb.build.prepareQuery(ctx); err != nil {
		return err
	}
	return scanWithInterceptors[*MentiQuery, *MentiGroupBy](ctx, mgb.build, mgb, mgb.build.inters, v)
}

func (mgb *MentiGroupBy) sqlScan(ctx context.Context, root *MentiQuery, v any) error {
	selector := root.sqlQuery(ctx).Select()
	aggregation := make([]string, 0, len(mgb.fns))
	for _, fn := range mgb.fns {
		aggregation = append(aggregation, fn(selector))
	}
	if len(selector.SelectedColumns()) == 0 {
		columns := make([]string, 0, len(*mgb.flds)+len(mgb.fns))
		for _, f := range *mgb.flds {
			columns = append(columns, selector.C(f))
		}
		columns = append(columns, aggregation...)
		selector.Select(columns...)
	}
	selector.GroupBy(selector.Columns(*mgb.flds...)...)
	if err := selector.Err(); err != nil {
		return err
	}
	rows := &sql.Rows{}
	query, args := selector.Query()
	if err := mgb.build.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}

// MentiSelect is the builder for selecting fields of Menti entities.
type MentiSelect struct {
	*MentiQuery
	selector
}

// Aggregate adds the given aggregation functions to the selector query.
func (ms *MentiSelect) Aggregate(fns ...AggregateFunc) *MentiSelect {
	ms.fns = append(ms.fns, fns...)
	return ms
}

// Scan applies the selector query and scans the result into the given value.
func (ms *MentiSelect) Scan(ctx context.Context, v any) error {
	ctx = setContextOp(ctx, ms.ctx, "Select")
	if err := ms.prepareQuery(ctx); err != nil {
		return err
	}
	return scanWithInterceptors[*MentiQuery, *MentiSelect](ctx, ms.MentiQuery, ms, ms.inters, v)
}

func (ms *MentiSelect) sqlScan(ctx context.Context, root *MentiQuery, v any) error {
	selector := root.sqlQuery(ctx)
	aggregation := make([]string, 0, len(ms.fns))
	for _, fn := range ms.fns {
		aggregation = append(aggregation, fn(selector))
	}
	switch n := len(*ms.selector.flds); {
	case n == 0 && len(aggregation) > 0:
		selector.Select(aggregation...)
	case n != 0 && len(aggregation) > 0:
		selector.AppendSelect(aggregation...)
	}
	rows := &sql.Rows{}
	query, args := selector.Query()
	if err := ms.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}
