// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"itamconnect/ent/internal"
	"itamconnect/ent/predicate"
	"itamconnect/ent/realexperience"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// RealExperienceDelete is the builder for deleting a RealExperience entity.
type RealExperienceDelete struct {
	config
	hooks    []Hook
	mutation *RealExperienceMutation
}

// Where appends a list predicates to the RealExperienceDelete builder.
func (red *RealExperienceDelete) Where(ps ...predicate.RealExperience) *RealExperienceDelete {
	red.mutation.Where(ps...)
	return red
}

// Exec executes the deletion query and returns how many vertices were deleted.
func (red *RealExperienceDelete) Exec(ctx context.Context) (int, error) {
	return withHooks(ctx, red.sqlExec, red.mutation, red.hooks)
}

// ExecX is like Exec, but panics if an error occurs.
func (red *RealExperienceDelete) ExecX(ctx context.Context) int {
	n, err := red.Exec(ctx)
	if err != nil {
		panic(err)
	}
	return n
}

func (red *RealExperienceDelete) sqlExec(ctx context.Context) (int, error) {
	_spec := sqlgraph.NewDeleteSpec(realexperience.Table, sqlgraph.NewFieldSpec(realexperience.FieldID, field.TypeInt))
	_spec.Node.Schema = red.schemaConfig.RealExperience
	ctx = internal.NewSchemaConfigContext(ctx, red.schemaConfig)
	if ps := red.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	affected, err := sqlgraph.DeleteNodes(ctx, red.driver, _spec)
	if err != nil && sqlgraph.IsConstraintError(err) {
		err = &ConstraintError{msg: err.Error(), wrap: err}
	}
	red.mutation.done = true
	return affected, err
}

// RealExperienceDeleteOne is the builder for deleting a single RealExperience entity.
type RealExperienceDeleteOne struct {
	red *RealExperienceDelete
}

// Where appends a list predicates to the RealExperienceDelete builder.
func (redo *RealExperienceDeleteOne) Where(ps ...predicate.RealExperience) *RealExperienceDeleteOne {
	redo.red.mutation.Where(ps...)
	return redo
}

// Exec executes the deletion query.
func (redo *RealExperienceDeleteOne) Exec(ctx context.Context) error {
	n, err := redo.red.Exec(ctx)
	switch {
	case err != nil:
		return err
	case n == 0:
		return &NotFoundError{realexperience.Label}
	default:
		return nil
	}
}

// ExecX is like Exec, but panics if an error occurs.
func (redo *RealExperienceDeleteOne) ExecX(ctx context.Context) {
	if err := redo.Exec(ctx); err != nil {
		panic(err)
	}
}
