// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"fmt"
	"itamconnect/ent/internal"
	"itamconnect/ent/predicate"
	"itamconnect/ent/realexperience"
	"math"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// RealExperienceQuery is the builder for querying RealExperience entities.
type RealExperienceQuery struct {
	config
	ctx        *QueryContext
	order      []realexperience.OrderOption
	inters     []Interceptor
	predicates []predicate.RealExperience
	withFKs    bool
	// intermediate query (i.e. traversal path).
	sql  *sql.Selector
	path func(context.Context) (*sql.Selector, error)
}

// Where adds a new predicate for the RealExperienceQuery builder.
func (req *RealExperienceQuery) Where(ps ...predicate.RealExperience) *RealExperienceQuery {
	req.predicates = append(req.predicates, ps...)
	return req
}

// Limit the number of records to be returned by this query.
func (req *RealExperienceQuery) Limit(limit int) *RealExperienceQuery {
	req.ctx.Limit = &limit
	return req
}

// Offset to start from.
func (req *RealExperienceQuery) Offset(offset int) *RealExperienceQuery {
	req.ctx.Offset = &offset
	return req
}

// Unique configures the query builder to filter duplicate records on query.
// By default, unique is set to true, and can be disabled using this method.
func (req *RealExperienceQuery) Unique(unique bool) *RealExperienceQuery {
	req.ctx.Unique = &unique
	return req
}

// Order specifies how the records should be ordered.
func (req *RealExperienceQuery) Order(o ...realexperience.OrderOption) *RealExperienceQuery {
	req.order = append(req.order, o...)
	return req
}

// First returns the first RealExperience entity from the query.
// Returns a *NotFoundError when no RealExperience was found.
func (req *RealExperienceQuery) First(ctx context.Context) (*RealExperience, error) {
	nodes, err := req.Limit(1).All(setContextOp(ctx, req.ctx, "First"))
	if err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nil, &NotFoundError{realexperience.Label}
	}
	return nodes[0], nil
}

// FirstX is like First, but panics if an error occurs.
func (req *RealExperienceQuery) FirstX(ctx context.Context) *RealExperience {
	node, err := req.First(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return node
}

// FirstID returns the first RealExperience ID from the query.
// Returns a *NotFoundError when no RealExperience ID was found.
func (req *RealExperienceQuery) FirstID(ctx context.Context) (id int, err error) {
	var ids []int
	if ids, err = req.Limit(1).IDs(setContextOp(ctx, req.ctx, "FirstID")); err != nil {
		return
	}
	if len(ids) == 0 {
		err = &NotFoundError{realexperience.Label}
		return
	}
	return ids[0], nil
}

// FirstIDX is like FirstID, but panics if an error occurs.
func (req *RealExperienceQuery) FirstIDX(ctx context.Context) int {
	id, err := req.FirstID(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return id
}

// Only returns a single RealExperience entity found by the query, ensuring it only returns one.
// Returns a *NotSingularError when more than one RealExperience entity is found.
// Returns a *NotFoundError when no RealExperience entities are found.
func (req *RealExperienceQuery) Only(ctx context.Context) (*RealExperience, error) {
	nodes, err := req.Limit(2).All(setContextOp(ctx, req.ctx, "Only"))
	if err != nil {
		return nil, err
	}
	switch len(nodes) {
	case 1:
		return nodes[0], nil
	case 0:
		return nil, &NotFoundError{realexperience.Label}
	default:
		return nil, &NotSingularError{realexperience.Label}
	}
}

// OnlyX is like Only, but panics if an error occurs.
func (req *RealExperienceQuery) OnlyX(ctx context.Context) *RealExperience {
	node, err := req.Only(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// OnlyID is like Only, but returns the only RealExperience ID in the query.
// Returns a *NotSingularError when more than one RealExperience ID is found.
// Returns a *NotFoundError when no entities are found.
func (req *RealExperienceQuery) OnlyID(ctx context.Context) (id int, err error) {
	var ids []int
	if ids, err = req.Limit(2).IDs(setContextOp(ctx, req.ctx, "OnlyID")); err != nil {
		return
	}
	switch len(ids) {
	case 1:
		id = ids[0]
	case 0:
		err = &NotFoundError{realexperience.Label}
	default:
		err = &NotSingularError{realexperience.Label}
	}
	return
}

// OnlyIDX is like OnlyID, but panics if an error occurs.
func (req *RealExperienceQuery) OnlyIDX(ctx context.Context) int {
	id, err := req.OnlyID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// All executes the query and returns a list of RealExperiences.
func (req *RealExperienceQuery) All(ctx context.Context) ([]*RealExperience, error) {
	ctx = setContextOp(ctx, req.ctx, "All")
	if err := req.prepareQuery(ctx); err != nil {
		return nil, err
	}
	qr := querierAll[[]*RealExperience, *RealExperienceQuery]()
	return withInterceptors[[]*RealExperience](ctx, req, qr, req.inters)
}

// AllX is like All, but panics if an error occurs.
func (req *RealExperienceQuery) AllX(ctx context.Context) []*RealExperience {
	nodes, err := req.All(ctx)
	if err != nil {
		panic(err)
	}
	return nodes
}

// IDs executes the query and returns a list of RealExperience IDs.
func (req *RealExperienceQuery) IDs(ctx context.Context) (ids []int, err error) {
	if req.ctx.Unique == nil && req.path != nil {
		req.Unique(true)
	}
	ctx = setContextOp(ctx, req.ctx, "IDs")
	if err = req.Select(realexperience.FieldID).Scan(ctx, &ids); err != nil {
		return nil, err
	}
	return ids, nil
}

// IDsX is like IDs, but panics if an error occurs.
func (req *RealExperienceQuery) IDsX(ctx context.Context) []int {
	ids, err := req.IDs(ctx)
	if err != nil {
		panic(err)
	}
	return ids
}

// Count returns the count of the given query.
func (req *RealExperienceQuery) Count(ctx context.Context) (int, error) {
	ctx = setContextOp(ctx, req.ctx, "Count")
	if err := req.prepareQuery(ctx); err != nil {
		return 0, err
	}
	return withInterceptors[int](ctx, req, querierCount[*RealExperienceQuery](), req.inters)
}

// CountX is like Count, but panics if an error occurs.
func (req *RealExperienceQuery) CountX(ctx context.Context) int {
	count, err := req.Count(ctx)
	if err != nil {
		panic(err)
	}
	return count
}

// Exist returns true if the query has elements in the graph.
func (req *RealExperienceQuery) Exist(ctx context.Context) (bool, error) {
	ctx = setContextOp(ctx, req.ctx, "Exist")
	switch _, err := req.FirstID(ctx); {
	case IsNotFound(err):
		return false, nil
	case err != nil:
		return false, fmt.Errorf("ent: check existence: %w", err)
	default:
		return true, nil
	}
}

// ExistX is like Exist, but panics if an error occurs.
func (req *RealExperienceQuery) ExistX(ctx context.Context) bool {
	exist, err := req.Exist(ctx)
	if err != nil {
		panic(err)
	}
	return exist
}

// Clone returns a duplicate of the RealExperienceQuery builder, including all associated steps. It can be
// used to prepare common query builders and use them differently after the clone is made.
func (req *RealExperienceQuery) Clone() *RealExperienceQuery {
	if req == nil {
		return nil
	}
	return &RealExperienceQuery{
		config:     req.config,
		ctx:        req.ctx.Clone(),
		order:      append([]realexperience.OrderOption{}, req.order...),
		inters:     append([]Interceptor{}, req.inters...),
		predicates: append([]predicate.RealExperience{}, req.predicates...),
		// clone intermediate query.
		sql:  req.sql.Clone(),
		path: req.path,
	}
}

// GroupBy is used to group vertices by one or more fields/columns.
// It is often used with aggregate functions, like: count, max, mean, min, sum.
//
// Example:
//
//	var v []struct {
//		Where string `json:"where,omitempty"`
//		Count int `json:"count,omitempty"`
//	}
//
//	client.RealExperience.Query().
//		GroupBy(realexperience.FieldWhere).
//		Aggregate(ent.Count()).
//		Scan(ctx, &v)
func (req *RealExperienceQuery) GroupBy(field string, fields ...string) *RealExperienceGroupBy {
	req.ctx.Fields = append([]string{field}, fields...)
	grbuild := &RealExperienceGroupBy{build: req}
	grbuild.flds = &req.ctx.Fields
	grbuild.label = realexperience.Label
	grbuild.scan = grbuild.Scan
	return grbuild
}

// Select allows the selection one or more fields/columns for the given query,
// instead of selecting all fields in the entity.
//
// Example:
//
//	var v []struct {
//		Where string `json:"where,omitempty"`
//	}
//
//	client.RealExperience.Query().
//		Select(realexperience.FieldWhere).
//		Scan(ctx, &v)
func (req *RealExperienceQuery) Select(fields ...string) *RealExperienceSelect {
	req.ctx.Fields = append(req.ctx.Fields, fields...)
	sbuild := &RealExperienceSelect{RealExperienceQuery: req}
	sbuild.label = realexperience.Label
	sbuild.flds, sbuild.scan = &req.ctx.Fields, sbuild.Scan
	return sbuild
}

// Aggregate returns a RealExperienceSelect configured with the given aggregations.
func (req *RealExperienceQuery) Aggregate(fns ...AggregateFunc) *RealExperienceSelect {
	return req.Select().Aggregate(fns...)
}

func (req *RealExperienceQuery) prepareQuery(ctx context.Context) error {
	for _, inter := range req.inters {
		if inter == nil {
			return fmt.Errorf("ent: uninitialized interceptor (forgotten import ent/runtime?)")
		}
		if trv, ok := inter.(Traverser); ok {
			if err := trv.Traverse(ctx, req); err != nil {
				return err
			}
		}
	}
	for _, f := range req.ctx.Fields {
		if !realexperience.ValidColumn(f) {
			return &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
		}
	}
	if req.path != nil {
		prev, err := req.path(ctx)
		if err != nil {
			return err
		}
		req.sql = prev
	}
	return nil
}

func (req *RealExperienceQuery) sqlAll(ctx context.Context, hooks ...queryHook) ([]*RealExperience, error) {
	var (
		nodes   = []*RealExperience{}
		withFKs = req.withFKs
		_spec   = req.querySpec()
	)
	if withFKs {
		_spec.Node.Columns = append(_spec.Node.Columns, realexperience.ForeignKeys...)
	}
	_spec.ScanValues = func(columns []string) ([]any, error) {
		return (*RealExperience).scanValues(nil, columns)
	}
	_spec.Assign = func(columns []string, values []any) error {
		node := &RealExperience{config: req.config}
		nodes = append(nodes, node)
		return node.assignValues(columns, values)
	}
	_spec.Node.Schema = req.schemaConfig.RealExperience
	ctx = internal.NewSchemaConfigContext(ctx, req.schemaConfig)
	for i := range hooks {
		hooks[i](ctx, _spec)
	}
	if err := sqlgraph.QueryNodes(ctx, req.driver, _spec); err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nodes, nil
	}
	return nodes, nil
}

func (req *RealExperienceQuery) sqlCount(ctx context.Context) (int, error) {
	_spec := req.querySpec()
	_spec.Node.Schema = req.schemaConfig.RealExperience
	ctx = internal.NewSchemaConfigContext(ctx, req.schemaConfig)
	_spec.Node.Columns = req.ctx.Fields
	if len(req.ctx.Fields) > 0 {
		_spec.Unique = req.ctx.Unique != nil && *req.ctx.Unique
	}
	return sqlgraph.CountNodes(ctx, req.driver, _spec)
}

func (req *RealExperienceQuery) querySpec() *sqlgraph.QuerySpec {
	_spec := sqlgraph.NewQuerySpec(realexperience.Table, realexperience.Columns, sqlgraph.NewFieldSpec(realexperience.FieldID, field.TypeInt))
	_spec.From = req.sql
	if unique := req.ctx.Unique; unique != nil {
		_spec.Unique = *unique
	} else if req.path != nil {
		_spec.Unique = true
	}
	if fields := req.ctx.Fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, realexperience.FieldID)
		for i := range fields {
			if fields[i] != realexperience.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, fields[i])
			}
		}
	}
	if ps := req.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if limit := req.ctx.Limit; limit != nil {
		_spec.Limit = *limit
	}
	if offset := req.ctx.Offset; offset != nil {
		_spec.Offset = *offset
	}
	if ps := req.order; len(ps) > 0 {
		_spec.Order = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	return _spec
}

func (req *RealExperienceQuery) sqlQuery(ctx context.Context) *sql.Selector {
	builder := sql.Dialect(req.driver.Dialect())
	t1 := builder.Table(realexperience.Table)
	columns := req.ctx.Fields
	if len(columns) == 0 {
		columns = realexperience.Columns
	}
	selector := builder.Select(t1.Columns(columns...)...).From(t1)
	if req.sql != nil {
		selector = req.sql
		selector.Select(selector.Columns(columns...)...)
	}
	if req.ctx.Unique != nil && *req.ctx.Unique {
		selector.Distinct()
	}
	t1.Schema(req.schemaConfig.RealExperience)
	ctx = internal.NewSchemaConfigContext(ctx, req.schemaConfig)
	selector.WithContext(ctx)
	for _, p := range req.predicates {
		p(selector)
	}
	for _, p := range req.order {
		p(selector)
	}
	if offset := req.ctx.Offset; offset != nil {
		// limit is mandatory for offset clause. We start
		// with default value, and override it below if needed.
		selector.Offset(*offset).Limit(math.MaxInt32)
	}
	if limit := req.ctx.Limit; limit != nil {
		selector.Limit(*limit)
	}
	return selector
}

// RealExperienceGroupBy is the group-by builder for RealExperience entities.
type RealExperienceGroupBy struct {
	selector
	build *RealExperienceQuery
}

// Aggregate adds the given aggregation functions to the group-by query.
func (regb *RealExperienceGroupBy) Aggregate(fns ...AggregateFunc) *RealExperienceGroupBy {
	regb.fns = append(regb.fns, fns...)
	return regb
}

// Scan applies the selector query and scans the result into the given value.
func (regb *RealExperienceGroupBy) Scan(ctx context.Context, v any) error {
	ctx = setContextOp(ctx, regb.build.ctx, "GroupBy")
	if err := regb.build.prepareQuery(ctx); err != nil {
		return err
	}
	return scanWithInterceptors[*RealExperienceQuery, *RealExperienceGroupBy](ctx, regb.build, regb, regb.build.inters, v)
}

func (regb *RealExperienceGroupBy) sqlScan(ctx context.Context, root *RealExperienceQuery, v any) error {
	selector := root.sqlQuery(ctx).Select()
	aggregation := make([]string, 0, len(regb.fns))
	for _, fn := range regb.fns {
		aggregation = append(aggregation, fn(selector))
	}
	if len(selector.SelectedColumns()) == 0 {
		columns := make([]string, 0, len(*regb.flds)+len(regb.fns))
		for _, f := range *regb.flds {
			columns = append(columns, selector.C(f))
		}
		columns = append(columns, aggregation...)
		selector.Select(columns...)
	}
	selector.GroupBy(selector.Columns(*regb.flds...)...)
	if err := selector.Err(); err != nil {
		return err
	}
	rows := &sql.Rows{}
	query, args := selector.Query()
	if err := regb.build.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}

// RealExperienceSelect is the builder for selecting fields of RealExperience entities.
type RealExperienceSelect struct {
	*RealExperienceQuery
	selector
}

// Aggregate adds the given aggregation functions to the selector query.
func (res *RealExperienceSelect) Aggregate(fns ...AggregateFunc) *RealExperienceSelect {
	res.fns = append(res.fns, fns...)
	return res
}

// Scan applies the selector query and scans the result into the given value.
func (res *RealExperienceSelect) Scan(ctx context.Context, v any) error {
	ctx = setContextOp(ctx, res.ctx, "Select")
	if err := res.prepareQuery(ctx); err != nil {
		return err
	}
	return scanWithInterceptors[*RealExperienceQuery, *RealExperienceSelect](ctx, res.RealExperienceQuery, res, res.inters, v)
}

func (res *RealExperienceSelect) sqlScan(ctx context.Context, root *RealExperienceQuery, v any) error {
	selector := root.sqlQuery(ctx)
	aggregation := make([]string, 0, len(res.fns))
	for _, fn := range res.fns {
		aggregation = append(aggregation, fn(selector))
	}
	switch n := len(*res.selector.flds); {
	case n == 0 && len(aggregation) > 0:
		selector.Select(aggregation...)
	case n != 0 && len(aggregation) > 0:
		selector.AppendSelect(aggregation...)
	}
	rows := &sql.Rows{}
	query, args := selector.Query()
	if err := res.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}
