// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"fmt"
	"itamconnect/ent/internal"
	"itamconnect/ent/mentor"
	"itamconnect/ent/predicate"
	"itamconnect/ent/roadmap"
	"math"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// RoadMapQuery is the builder for querying RoadMap entities.
type RoadMapQuery struct {
	config
	ctx        *QueryContext
	order      []roadmap.OrderOption
	inters     []Interceptor
	predicates []predicate.RoadMap
	withAuthor *MentorQuery
	withFKs    bool
	// intermediate query (i.e. traversal path).
	sql  *sql.Selector
	path func(context.Context) (*sql.Selector, error)
}

// Where adds a new predicate for the RoadMapQuery builder.
func (rmq *RoadMapQuery) Where(ps ...predicate.RoadMap) *RoadMapQuery {
	rmq.predicates = append(rmq.predicates, ps...)
	return rmq
}

// Limit the number of records to be returned by this query.
func (rmq *RoadMapQuery) Limit(limit int) *RoadMapQuery {
	rmq.ctx.Limit = &limit
	return rmq
}

// Offset to start from.
func (rmq *RoadMapQuery) Offset(offset int) *RoadMapQuery {
	rmq.ctx.Offset = &offset
	return rmq
}

// Unique configures the query builder to filter duplicate records on query.
// By default, unique is set to true, and can be disabled using this method.
func (rmq *RoadMapQuery) Unique(unique bool) *RoadMapQuery {
	rmq.ctx.Unique = &unique
	return rmq
}

// Order specifies how the records should be ordered.
func (rmq *RoadMapQuery) Order(o ...roadmap.OrderOption) *RoadMapQuery {
	rmq.order = append(rmq.order, o...)
	return rmq
}

// QueryAuthor chains the current query on the "author" edge.
func (rmq *RoadMapQuery) QueryAuthor() *MentorQuery {
	query := (&MentorClient{config: rmq.config}).Query()
	query.path = func(ctx context.Context) (fromU *sql.Selector, err error) {
		if err := rmq.prepareQuery(ctx); err != nil {
			return nil, err
		}
		selector := rmq.sqlQuery(ctx)
		if err := selector.Err(); err != nil {
			return nil, err
		}
		step := sqlgraph.NewStep(
			sqlgraph.From(roadmap.Table, roadmap.FieldID, selector),
			sqlgraph.To(mentor.Table, mentor.FieldID),
			sqlgraph.Edge(sqlgraph.M2O, false, roadmap.AuthorTable, roadmap.AuthorColumn),
		)
		schemaConfig := rmq.schemaConfig
		step.To.Schema = schemaConfig.Mentor
		step.Edge.Schema = schemaConfig.RoadMap
		fromU = sqlgraph.SetNeighbors(rmq.driver.Dialect(), step)
		return fromU, nil
	}
	return query
}

// First returns the first RoadMap entity from the query.
// Returns a *NotFoundError when no RoadMap was found.
func (rmq *RoadMapQuery) First(ctx context.Context) (*RoadMap, error) {
	nodes, err := rmq.Limit(1).All(setContextOp(ctx, rmq.ctx, "First"))
	if err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nil, &NotFoundError{roadmap.Label}
	}
	return nodes[0], nil
}

// FirstX is like First, but panics if an error occurs.
func (rmq *RoadMapQuery) FirstX(ctx context.Context) *RoadMap {
	node, err := rmq.First(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return node
}

// FirstID returns the first RoadMap ID from the query.
// Returns a *NotFoundError when no RoadMap ID was found.
func (rmq *RoadMapQuery) FirstID(ctx context.Context) (id int, err error) {
	var ids []int
	if ids, err = rmq.Limit(1).IDs(setContextOp(ctx, rmq.ctx, "FirstID")); err != nil {
		return
	}
	if len(ids) == 0 {
		err = &NotFoundError{roadmap.Label}
		return
	}
	return ids[0], nil
}

// FirstIDX is like FirstID, but panics if an error occurs.
func (rmq *RoadMapQuery) FirstIDX(ctx context.Context) int {
	id, err := rmq.FirstID(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return id
}

// Only returns a single RoadMap entity found by the query, ensuring it only returns one.
// Returns a *NotSingularError when more than one RoadMap entity is found.
// Returns a *NotFoundError when no RoadMap entities are found.
func (rmq *RoadMapQuery) Only(ctx context.Context) (*RoadMap, error) {
	nodes, err := rmq.Limit(2).All(setContextOp(ctx, rmq.ctx, "Only"))
	if err != nil {
		return nil, err
	}
	switch len(nodes) {
	case 1:
		return nodes[0], nil
	case 0:
		return nil, &NotFoundError{roadmap.Label}
	default:
		return nil, &NotSingularError{roadmap.Label}
	}
}

// OnlyX is like Only, but panics if an error occurs.
func (rmq *RoadMapQuery) OnlyX(ctx context.Context) *RoadMap {
	node, err := rmq.Only(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// OnlyID is like Only, but returns the only RoadMap ID in the query.
// Returns a *NotSingularError when more than one RoadMap ID is found.
// Returns a *NotFoundError when no entities are found.
func (rmq *RoadMapQuery) OnlyID(ctx context.Context) (id int, err error) {
	var ids []int
	if ids, err = rmq.Limit(2).IDs(setContextOp(ctx, rmq.ctx, "OnlyID")); err != nil {
		return
	}
	switch len(ids) {
	case 1:
		id = ids[0]
	case 0:
		err = &NotFoundError{roadmap.Label}
	default:
		err = &NotSingularError{roadmap.Label}
	}
	return
}

// OnlyIDX is like OnlyID, but panics if an error occurs.
func (rmq *RoadMapQuery) OnlyIDX(ctx context.Context) int {
	id, err := rmq.OnlyID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// All executes the query and returns a list of RoadMaps.
func (rmq *RoadMapQuery) All(ctx context.Context) ([]*RoadMap, error) {
	ctx = setContextOp(ctx, rmq.ctx, "All")
	if err := rmq.prepareQuery(ctx); err != nil {
		return nil, err
	}
	qr := querierAll[[]*RoadMap, *RoadMapQuery]()
	return withInterceptors[[]*RoadMap](ctx, rmq, qr, rmq.inters)
}

// AllX is like All, but panics if an error occurs.
func (rmq *RoadMapQuery) AllX(ctx context.Context) []*RoadMap {
	nodes, err := rmq.All(ctx)
	if err != nil {
		panic(err)
	}
	return nodes
}

// IDs executes the query and returns a list of RoadMap IDs.
func (rmq *RoadMapQuery) IDs(ctx context.Context) (ids []int, err error) {
	if rmq.ctx.Unique == nil && rmq.path != nil {
		rmq.Unique(true)
	}
	ctx = setContextOp(ctx, rmq.ctx, "IDs")
	if err = rmq.Select(roadmap.FieldID).Scan(ctx, &ids); err != nil {
		return nil, err
	}
	return ids, nil
}

// IDsX is like IDs, but panics if an error occurs.
func (rmq *RoadMapQuery) IDsX(ctx context.Context) []int {
	ids, err := rmq.IDs(ctx)
	if err != nil {
		panic(err)
	}
	return ids
}

// Count returns the count of the given query.
func (rmq *RoadMapQuery) Count(ctx context.Context) (int, error) {
	ctx = setContextOp(ctx, rmq.ctx, "Count")
	if err := rmq.prepareQuery(ctx); err != nil {
		return 0, err
	}
	return withInterceptors[int](ctx, rmq, querierCount[*RoadMapQuery](), rmq.inters)
}

// CountX is like Count, but panics if an error occurs.
func (rmq *RoadMapQuery) CountX(ctx context.Context) int {
	count, err := rmq.Count(ctx)
	if err != nil {
		panic(err)
	}
	return count
}

// Exist returns true if the query has elements in the graph.
func (rmq *RoadMapQuery) Exist(ctx context.Context) (bool, error) {
	ctx = setContextOp(ctx, rmq.ctx, "Exist")
	switch _, err := rmq.FirstID(ctx); {
	case IsNotFound(err):
		return false, nil
	case err != nil:
		return false, fmt.Errorf("ent: check existence: %w", err)
	default:
		return true, nil
	}
}

// ExistX is like Exist, but panics if an error occurs.
func (rmq *RoadMapQuery) ExistX(ctx context.Context) bool {
	exist, err := rmq.Exist(ctx)
	if err != nil {
		panic(err)
	}
	return exist
}

// Clone returns a duplicate of the RoadMapQuery builder, including all associated steps. It can be
// used to prepare common query builders and use them differently after the clone is made.
func (rmq *RoadMapQuery) Clone() *RoadMapQuery {
	if rmq == nil {
		return nil
	}
	return &RoadMapQuery{
		config:     rmq.config,
		ctx:        rmq.ctx.Clone(),
		order:      append([]roadmap.OrderOption{}, rmq.order...),
		inters:     append([]Interceptor{}, rmq.inters...),
		predicates: append([]predicate.RoadMap{}, rmq.predicates...),
		withAuthor: rmq.withAuthor.Clone(),
		// clone intermediate query.
		sql:  rmq.sql.Clone(),
		path: rmq.path,
	}
}

// WithAuthor tells the query-builder to eager-load the nodes that are connected to
// the "author" edge. The optional arguments are used to configure the query builder of the edge.
func (rmq *RoadMapQuery) WithAuthor(opts ...func(*MentorQuery)) *RoadMapQuery {
	query := (&MentorClient{config: rmq.config}).Query()
	for _, opt := range opts {
		opt(query)
	}
	rmq.withAuthor = query
	return rmq
}

// GroupBy is used to group vertices by one or more fields/columns.
// It is often used with aggregate functions, like: count, max, mean, min, sum.
//
// Example:
//
//	var v []struct {
//		Name string `json:"name,omitempty"`
//		Count int `json:"count,omitempty"`
//	}
//
//	client.RoadMap.Query().
//		GroupBy(roadmap.FieldName).
//		Aggregate(ent.Count()).
//		Scan(ctx, &v)
func (rmq *RoadMapQuery) GroupBy(field string, fields ...string) *RoadMapGroupBy {
	rmq.ctx.Fields = append([]string{field}, fields...)
	grbuild := &RoadMapGroupBy{build: rmq}
	grbuild.flds = &rmq.ctx.Fields
	grbuild.label = roadmap.Label
	grbuild.scan = grbuild.Scan
	return grbuild
}

// Select allows the selection one or more fields/columns for the given query,
// instead of selecting all fields in the entity.
//
// Example:
//
//	var v []struct {
//		Name string `json:"name,omitempty"`
//	}
//
//	client.RoadMap.Query().
//		Select(roadmap.FieldName).
//		Scan(ctx, &v)
func (rmq *RoadMapQuery) Select(fields ...string) *RoadMapSelect {
	rmq.ctx.Fields = append(rmq.ctx.Fields, fields...)
	sbuild := &RoadMapSelect{RoadMapQuery: rmq}
	sbuild.label = roadmap.Label
	sbuild.flds, sbuild.scan = &rmq.ctx.Fields, sbuild.Scan
	return sbuild
}

// Aggregate returns a RoadMapSelect configured with the given aggregations.
func (rmq *RoadMapQuery) Aggregate(fns ...AggregateFunc) *RoadMapSelect {
	return rmq.Select().Aggregate(fns...)
}

func (rmq *RoadMapQuery) prepareQuery(ctx context.Context) error {
	for _, inter := range rmq.inters {
		if inter == nil {
			return fmt.Errorf("ent: uninitialized interceptor (forgotten import ent/runtime?)")
		}
		if trv, ok := inter.(Traverser); ok {
			if err := trv.Traverse(ctx, rmq); err != nil {
				return err
			}
		}
	}
	for _, f := range rmq.ctx.Fields {
		if !roadmap.ValidColumn(f) {
			return &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
		}
	}
	if rmq.path != nil {
		prev, err := rmq.path(ctx)
		if err != nil {
			return err
		}
		rmq.sql = prev
	}
	return nil
}

func (rmq *RoadMapQuery) sqlAll(ctx context.Context, hooks ...queryHook) ([]*RoadMap, error) {
	var (
		nodes       = []*RoadMap{}
		withFKs     = rmq.withFKs
		_spec       = rmq.querySpec()
		loadedTypes = [1]bool{
			rmq.withAuthor != nil,
		}
	)
	if rmq.withAuthor != nil {
		withFKs = true
	}
	if withFKs {
		_spec.Node.Columns = append(_spec.Node.Columns, roadmap.ForeignKeys...)
	}
	_spec.ScanValues = func(columns []string) ([]any, error) {
		return (*RoadMap).scanValues(nil, columns)
	}
	_spec.Assign = func(columns []string, values []any) error {
		node := &RoadMap{config: rmq.config}
		nodes = append(nodes, node)
		node.Edges.loadedTypes = loadedTypes
		return node.assignValues(columns, values)
	}
	_spec.Node.Schema = rmq.schemaConfig.RoadMap
	ctx = internal.NewSchemaConfigContext(ctx, rmq.schemaConfig)
	for i := range hooks {
		hooks[i](ctx, _spec)
	}
	if err := sqlgraph.QueryNodes(ctx, rmq.driver, _spec); err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nodes, nil
	}
	if query := rmq.withAuthor; query != nil {
		if err := rmq.loadAuthor(ctx, query, nodes, nil,
			func(n *RoadMap, e *Mentor) { n.Edges.Author = e }); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

func (rmq *RoadMapQuery) loadAuthor(ctx context.Context, query *MentorQuery, nodes []*RoadMap, init func(*RoadMap), assign func(*RoadMap, *Mentor)) error {
	ids := make([]int, 0, len(nodes))
	nodeids := make(map[int][]*RoadMap)
	for i := range nodes {
		if nodes[i].road_map_author == nil {
			continue
		}
		fk := *nodes[i].road_map_author
		if _, ok := nodeids[fk]; !ok {
			ids = append(ids, fk)
		}
		nodeids[fk] = append(nodeids[fk], nodes[i])
	}
	if len(ids) == 0 {
		return nil
	}
	query.Where(mentor.IDIn(ids...))
	neighbors, err := query.All(ctx)
	if err != nil {
		return err
	}
	for _, n := range neighbors {
		nodes, ok := nodeids[n.ID]
		if !ok {
			return fmt.Errorf(`unexpected foreign-key "road_map_author" returned %v`, n.ID)
		}
		for i := range nodes {
			assign(nodes[i], n)
		}
	}
	return nil
}

func (rmq *RoadMapQuery) sqlCount(ctx context.Context) (int, error) {
	_spec := rmq.querySpec()
	_spec.Node.Schema = rmq.schemaConfig.RoadMap
	ctx = internal.NewSchemaConfigContext(ctx, rmq.schemaConfig)
	_spec.Node.Columns = rmq.ctx.Fields
	if len(rmq.ctx.Fields) > 0 {
		_spec.Unique = rmq.ctx.Unique != nil && *rmq.ctx.Unique
	}
	return sqlgraph.CountNodes(ctx, rmq.driver, _spec)
}

func (rmq *RoadMapQuery) querySpec() *sqlgraph.QuerySpec {
	_spec := sqlgraph.NewQuerySpec(roadmap.Table, roadmap.Columns, sqlgraph.NewFieldSpec(roadmap.FieldID, field.TypeInt))
	_spec.From = rmq.sql
	if unique := rmq.ctx.Unique; unique != nil {
		_spec.Unique = *unique
	} else if rmq.path != nil {
		_spec.Unique = true
	}
	if fields := rmq.ctx.Fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, roadmap.FieldID)
		for i := range fields {
			if fields[i] != roadmap.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, fields[i])
			}
		}
	}
	if ps := rmq.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if limit := rmq.ctx.Limit; limit != nil {
		_spec.Limit = *limit
	}
	if offset := rmq.ctx.Offset; offset != nil {
		_spec.Offset = *offset
	}
	if ps := rmq.order; len(ps) > 0 {
		_spec.Order = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	return _spec
}

func (rmq *RoadMapQuery) sqlQuery(ctx context.Context) *sql.Selector {
	builder := sql.Dialect(rmq.driver.Dialect())
	t1 := builder.Table(roadmap.Table)
	columns := rmq.ctx.Fields
	if len(columns) == 0 {
		columns = roadmap.Columns
	}
	selector := builder.Select(t1.Columns(columns...)...).From(t1)
	if rmq.sql != nil {
		selector = rmq.sql
		selector.Select(selector.Columns(columns...)...)
	}
	if rmq.ctx.Unique != nil && *rmq.ctx.Unique {
		selector.Distinct()
	}
	t1.Schema(rmq.schemaConfig.RoadMap)
	ctx = internal.NewSchemaConfigContext(ctx, rmq.schemaConfig)
	selector.WithContext(ctx)
	for _, p := range rmq.predicates {
		p(selector)
	}
	for _, p := range rmq.order {
		p(selector)
	}
	if offset := rmq.ctx.Offset; offset != nil {
		// limit is mandatory for offset clause. We start
		// with default value, and override it below if needed.
		selector.Offset(*offset).Limit(math.MaxInt32)
	}
	if limit := rmq.ctx.Limit; limit != nil {
		selector.Limit(*limit)
	}
	return selector
}

// RoadMapGroupBy is the group-by builder for RoadMap entities.
type RoadMapGroupBy struct {
	selector
	build *RoadMapQuery
}

// Aggregate adds the given aggregation functions to the group-by query.
func (rmgb *RoadMapGroupBy) Aggregate(fns ...AggregateFunc) *RoadMapGroupBy {
	rmgb.fns = append(rmgb.fns, fns...)
	return rmgb
}

// Scan applies the selector query and scans the result into the given value.
func (rmgb *RoadMapGroupBy) Scan(ctx context.Context, v any) error {
	ctx = setContextOp(ctx, rmgb.build.ctx, "GroupBy")
	if err := rmgb.build.prepareQuery(ctx); err != nil {
		return err
	}
	return scanWithInterceptors[*RoadMapQuery, *RoadMapGroupBy](ctx, rmgb.build, rmgb, rmgb.build.inters, v)
}

func (rmgb *RoadMapGroupBy) sqlScan(ctx context.Context, root *RoadMapQuery, v any) error {
	selector := root.sqlQuery(ctx).Select()
	aggregation := make([]string, 0, len(rmgb.fns))
	for _, fn := range rmgb.fns {
		aggregation = append(aggregation, fn(selector))
	}
	if len(selector.SelectedColumns()) == 0 {
		columns := make([]string, 0, len(*rmgb.flds)+len(rmgb.fns))
		for _, f := range *rmgb.flds {
			columns = append(columns, selector.C(f))
		}
		columns = append(columns, aggregation...)
		selector.Select(columns...)
	}
	selector.GroupBy(selector.Columns(*rmgb.flds...)...)
	if err := selector.Err(); err != nil {
		return err
	}
	rows := &sql.Rows{}
	query, args := selector.Query()
	if err := rmgb.build.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}

// RoadMapSelect is the builder for selecting fields of RoadMap entities.
type RoadMapSelect struct {
	*RoadMapQuery
	selector
}

// Aggregate adds the given aggregation functions to the selector query.
func (rms *RoadMapSelect) Aggregate(fns ...AggregateFunc) *RoadMapSelect {
	rms.fns = append(rms.fns, fns...)
	return rms
}

// Scan applies the selector query and scans the result into the given value.
func (rms *RoadMapSelect) Scan(ctx context.Context, v any) error {
	ctx = setContextOp(ctx, rms.ctx, "Select")
	if err := rms.prepareQuery(ctx); err != nil {
		return err
	}
	return scanWithInterceptors[*RoadMapQuery, *RoadMapSelect](ctx, rms.RoadMapQuery, rms, rms.inters, v)
}

func (rms *RoadMapSelect) sqlScan(ctx context.Context, root *RoadMapQuery, v any) error {
	selector := root.sqlQuery(ctx)
	aggregation := make([]string, 0, len(rms.fns))
	for _, fn := range rms.fns {
		aggregation = append(aggregation, fn(selector))
	}
	switch n := len(*rms.selector.flds); {
	case n == 0 && len(aggregation) > 0:
		selector.Select(aggregation...)
	case n != 0 && len(aggregation) > 0:
		selector.AppendSelect(aggregation...)
	}
	rows := &sql.Rows{}
	query, args := selector.Query()
	if err := rms.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}
