// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"itamconnect/ent/internal"
	"itamconnect/ent/predicate"
	"itamconnect/ent/roadmap"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// RoadMapDelete is the builder for deleting a RoadMap entity.
type RoadMapDelete struct {
	config
	hooks    []Hook
	mutation *RoadMapMutation
}

// Where appends a list predicates to the RoadMapDelete builder.
func (rmd *RoadMapDelete) Where(ps ...predicate.RoadMap) *RoadMapDelete {
	rmd.mutation.Where(ps...)
	return rmd
}

// Exec executes the deletion query and returns how many vertices were deleted.
func (rmd *RoadMapDelete) Exec(ctx context.Context) (int, error) {
	return withHooks(ctx, rmd.sqlExec, rmd.mutation, rmd.hooks)
}

// ExecX is like Exec, but panics if an error occurs.
func (rmd *RoadMapDelete) ExecX(ctx context.Context) int {
	n, err := rmd.Exec(ctx)
	if err != nil {
		panic(err)
	}
	return n
}

func (rmd *RoadMapDelete) sqlExec(ctx context.Context) (int, error) {
	_spec := sqlgraph.NewDeleteSpec(roadmap.Table, sqlgraph.NewFieldSpec(roadmap.FieldID, field.TypeInt))
	_spec.Node.Schema = rmd.schemaConfig.RoadMap
	ctx = internal.NewSchemaConfigContext(ctx, rmd.schemaConfig)
	if ps := rmd.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	affected, err := sqlgraph.DeleteNodes(ctx, rmd.driver, _spec)
	if err != nil && sqlgraph.IsConstraintError(err) {
		err = &ConstraintError{msg: err.Error(), wrap: err}
	}
	rmd.mutation.done = true
	return affected, err
}

// RoadMapDeleteOne is the builder for deleting a single RoadMap entity.
type RoadMapDeleteOne struct {
	rmd *RoadMapDelete
}

// Where appends a list predicates to the RoadMapDelete builder.
func (rmdo *RoadMapDeleteOne) Where(ps ...predicate.RoadMap) *RoadMapDeleteOne {
	rmdo.rmd.mutation.Where(ps...)
	return rmdo
}

// Exec executes the deletion query.
func (rmdo *RoadMapDeleteOne) Exec(ctx context.Context) error {
	n, err := rmdo.rmd.Exec(ctx)
	switch {
	case err != nil:
		return err
	case n == 0:
		return &NotFoundError{roadmap.Label}
	default:
		return nil
	}
}

// ExecX is like Exec, but panics if an error occurs.
func (rmdo *RoadMapDeleteOne) ExecX(ctx context.Context) {
	if err := rmdo.Exec(ctx); err != nil {
		panic(err)
	}
}
